#!/bin/bash

# Used for starting terminal apps in urxvt directly
# It ensures bash profile gets loaded before starting
# May be unable to support non-quotable args such as --some-arg.
urxvt -e bash -ci "$*"
